name: Python application
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
    # you can change to "3.13" to match local, but 3.11 is fine too
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas python-dotenv pytest pytest-cov

    - name: Run tests with 100% coverage gate
      run: |
        pytest --cov=app --cov-report=term-missing --cov-fail-under=100 tests/
